[project]
name = "p2f-pydantic"
version = "0.0.4"
description = "Pydantic library to define the data types of the Past to Future project API."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
]
